server {
    listen 80;
    server_name localhost;

    # Servir archivos estáticos de la aplicación React
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    resolver 127.0.0.11 valid=30s;

    # Proxy Inverso hacia el contenedor del Backend en la red de Docker
    location /api {
        proxy_pass http://nvr-backend:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        
        # Ajustes optimizados para WebRTC / WebSockets y streaming continuo
        proxy_connect_timeout 7s;
        proxy_send_timeout 86400s;
        proxy_read_timeout 86400s;
    }

    location ~ ^/whep/(?<node_ip>[0-9\.]+)/(?<stream_path>.+)$ {
        # Redirigir de forma transparente al puerto 8889 del nodo edge correspondiente
        proxy_pass http://$node_ip:8889/$stream_path;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        
        # Deshabilitar buffering para evitar latencia en la negociación WebRTC SDP
        proxy_buffering off;
        
        proxy_connect_timeout 5s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}